version: "3"
services:
  backend:
    container_name: singmeta_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    expose:
      - "5002"
    environment:
      NODE_ENV: production

    links:
      - mongodb
    depends_on:
      - mongodb

    networks:
      - febnine-net

  gameserver:
    container_name: singmeta_gameserver
    build:
      context: ./Phaser3
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    expose:
      - "3000"

    networks:
      - febnine-net

  mongodb:
    image: mongo
    container_name: singmetadb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
    networks:
      - "qualiexplore_net"
      - febnine-net

  mongo-seed:
    build:
      context: ./mongo_seed
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    networks:
      - "qualiexplore_net"
      - febnine-net

networks:
  febnine-net:
  qualiexplore_net:
